### ISSUE TITLE
Cannot run any Subtext tests due to exception creating test database

### ISSUE THREAD

**Issue by jeremy-jameson** [technology-toolbox/Subtext#1]
When running the tests, an **IndexOutOfRangeException** occurs in Microsoft.SqlServer.Smo.dll:

> Index was outside the bounds of the array.
````
   at Microsoft.SqlServer.Management.Smo.SqlPropertyMetadataProvider.PropertyNameToIDLookupWithException(String propertyName, PropertyAccessPurpose pap)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.LookupID(String propertyName, PropertyAccessPurpose pap)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.SetValueWithConsistencyCheck(String propertyName, Object value, Boolean allowNull)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.SetValueWithConsistencyCheck(String propertyName, Object value)
   at Microsoft.SqlServer.Management.Smo.DatabaseOptions.set_AutoClose(Boolean value)
   at UnitTests.Subtext.DatabaseHelper.CreateDb(Server server, String databaseName, String directory) in c:\NotBackedUp\GitHub\technology-toolbox\Subtext\src\UnitTests.Subtext\DatabaseHelper.cs:line 159
   at UnitTests.Subtext.DatabaseHelper.CreateDatabase(String serverName, String databaseName, String directory) in c:\NotBackedUp\GitHub\technology-toolbox\Subtext\src\UnitTests.Subtext\DatabaseHelper.cs:line 35
   at UnitTests.Subtext.DatabaseHelper.CreateAndInstallDatabase(ConnectionString connectionString, String databaseName, String directory) in c:\NotBackedUp\GitHub\technology-toolbox\Subtext\src\UnitTests.Subtext\DatabaseHelper.cs:line 17
   at UnitTests.Subtext.AssemblySetUpAndCleanUp.SetUp() in c:\NotBackedUp\GitHub\technology-toolbox\Subtext\src\UnitTests.Subtext\AssemblySetUpAndCleanUp.cs:line 23
````

**Comment by jeremy-jameson** [comment]
This is due to incompatibilities between the SQL Server Management Objects (SMO) assemblies located in the **src\Dependencies** folder and newer versions of SQL Server Express Edition. The "reference" assemblies are from SQL Server 2005 -- which do not work with later versions such as SQL Server 2008.

References:

[SMO, sqlserver2008](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/b39d42c9-d2e8-4dcb-8cf6-846ac76bbfcc/smo-sqlserver2008?forum=sqlsmoanddmo)

[Backward Compatibility in SMO](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008/dd206977(v=sql.100))
